changes in input value with edge cases
srujandeshpande/dice-on-demand pull request #11
Opened 2020-11-07 11:01 UTC by mehulsatardekar

made a changes in input value with min and max attributes as well as added a edge case if some user tries to add number through input bigger than expected value will show an error msg through alert box

2020-11-07 18:00 UTC, srujandeshpande requested changes
Please remove the max

2020-11-07 18:00 UTC, srujandeshpande commented on templates/dice_page.html
> +  <input type="number" value="6" min="0" max="6" id="dicesides"></input>
Min looks good. It would be great if max can be left open, that way larger dice can also be rolled

2020-11-09 06:02 UTC, mehulsatardekar reviewed
made a changes as you suggested.

2020-11-09 12:00 UTC, srujandeshpande approved these changes
Looks good!

2020-11-09 12:01 UTC, srujandeshpande commented
Thanks @mehulsatardekar looks great!

2020-11-09 12:02 UTC, merged